CREATE TABLE IF NOT EXISTS figures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT,
    series_title TEXT,
    manufacturer TEXT,
    release_date TEXT,
    official_price INTEGER,
    height_mm INTEGER,
    scale TEXT,
    is_articulated INTEGER DEFAULT 0,
    is_limited INTEGER DEFAULT 0,
    status TEXT,
    product_url TEXT,
    image_url TEXT,
    source TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    figure_id INTEGER NOT NULL REFERENCES figures(id) ON DELETE CASCADE,
    shop_name TEXT NOT NULL,
    price INTEGER NOT NULL,
    condition TEXT,
    stock_status TEXT,
    checked_date TEXT NOT NULL,
    product_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS collection (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    figure_id INTEGER NOT NULL UNIQUE REFERENCES figures(id) ON DELETE CASCADE,
    ownership_status TEXT NOT NULL,
    purchase_price INTEGER,
    purchase_shop TEXT,
    purchase_date TEXT,
    is_opened INTEGER DEFAULT 0,
    display_location TEXT,
    memo TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_figures_brand ON figures(brand);
CREATE INDEX IF NOT EXISTS idx_figures_release_date ON figures(release_date);
CREATE INDEX IF NOT EXISTS idx_price_records_figure_date ON price_records(figure_id, checked_date);
CREATE INDEX IF NOT EXISTS idx_collection_status ON collection(ownership_status);
